### ISSUE TITLE
Cursor() issue on model find

### ISSUE THREAD

**Issue by porvas** [vikpe/mongoose-mpath#1]
I am getting an error here:

var childCursor = self.model(this.constructor.modelName).find({parent: this._id}).cursor();

it says that the cursor function is not defined. I have changed to stream() and it works fine.

Do you know why is that a problem? Thanks

**Comment by vikpe** [comment]
No idea, but I'll look into it asap. Thanks for the notice!

**Comment by vikpe** [comment]
@porvas have you updated/installed the latest dependencies? (`npm update`)

I tried replacing `.cursor()` with `.stream()` and got the following warning:
```
DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, 
use Query.prototype.cursor() instead
```

**Comment by porvas** [comment]
yes i just did and i still get: 

TypeError: self.model(...).find(...).cursor is not a function
    at model.preRemove (C:\Users\Porfyrios\projects\meanjs\node_modules\mongoose-mpath\lib\mpath.js:99:89)

when i delete a document.

**Comment by vikpe** [comment]
Perhaps its a cache thing? Try deleting `/node_modules/` and then re-install (`npm install`).

What version of node and MongoDB are you running?

**Comment by porvas** [comment]
It was my mongoose version after all. Thanks for the quick response!
