### ISSUE TITLE
getChildrenTree does not return mongoose documents

### ISSUE THREAD

**Issue by TonyGao** [vikpe/mongoose-mpath#10]
Hi, there

I use this plugin for tree structure, I can insert a node to the tree. The path and parent fields work as expected. 

But, when I use this model to output the tree as json, the framework tell me 
> Cannot set property 'rootDoc' of undefined

I use .find to get a model array, so I use department[0] as the model. (Sorry for the issue title, I can't modify it now)

Any advice for this situation?

```javascript  
async findAll() {
    const department = await this.ctx.model.Department.find({ isTop: true }).exec();
    const data = await department[0].getChildrenTree();
    return data;
  }
```
modal
```javascript
'use strict';

module.exports = app => {
  const mongoose = app.mongoose;
  const objectId = mongoose.Schema.Types.ObjectId;
  const DepartmentSchema = new mongoose.Schema({
    label: {
      type: String,
      require: true,
      unique: true
    },
    isTop: {
      type: Boolean,
      require: true,
      default: false,
    },
    isDepartment: {
      type: Boolean,
      require: true,
      default: true,
    },
    code: {
      type: String,
    },
    orderNum: {
      type: Number,
    },
    manager: {
      type: objectId, ref: 'User',
    },
    viceManager: {
      type: objectId, ref: 'User',
    },
    state: {
      type: Boolean,
      default: true,
    },
    comment: {
      type: String,
    },
  });
  DepartmentSchema.plugin(require('mongoose-mpath'));

  return mongoose.model('department', DepartmentSchema);
};
```

**Comment by vikpe** [comment]
@TonyGao `find()` returns [plain objects by default](https://mongoosejs.com/docs/api.html#query_Query-lean) (`options.lean = true`). In order to return mongoose documents you need to pass `options.lean = false`.

```js
const data = await department[0].getChildrenTree({options: {lean: false;});
```

I should probably add a note on this in the readme.

**Comment by TonyGao** [comment]
@vikpe well, it's not contain children with options {lean: false}, but {lean: true} work perfectly as I want, thank you so much. 

By the way if you can add some note in document that's will be really helpful for the user, because the current example is just process of creating(insert data), but I think method .getChildrenTree is always in the situation of reading(find data).

**Comment by ViloCat** [comment]
Hey, I came up with the same issue as some others. So, when using getChildrenTree(); (by the way, getChildrenTree() breaks, I need at least to write getChildrenTree({}); in order not to), if {} is left empty, there is no "children" field at all. However, as @TonyGao said, it seems to work when writing "{lean: true}". So, in theory, the documents returned with "lean=true" are not mongoose documents (as the documentation says). So, is there any actual way to do a getChildrenTree() with all of the children fields filled with mongoose documents at all levels of the returned tree?

**Comment by vikpe** [comment]
@ViloCat Thank you for reporting these issues. I'll fix the 'getChildrenTree()' default args and try to make it work with 'lean: false'.

I'm abroad with no laptop so it will have to wait until next week.
