### ISSUE TITLE
Unable to sort results by path from database queries

### ISSUE THREAD

**Issue by kavadas** [vikpe/mongoose-mpath#16]
Hi,

That's a really promising implementation of materialized paths. Nice work!
I am facing an issue. Currently the generated path of each document includes also it's ID. This makes it impossible to sort documents by an other field. There is no way to sort two documents of the same parent. Removing the last ID from the path will allow to sort properly in our queries with something like that:
`sort: {
        path: 1,
        ordering: 1
      }`
Or:
`sort: {
        path: 1,
        title: 1
      }`

I hope this makes sense.

Regards

**Comment by vikpe** [comment]
@kavadas thanks for posting this issue.

I'll look into this and try to find a good solution. However I'm going abroad so it will have to wait until July 23.

**Comment by kavadas** [comment]
Thank you for the response. Have a nice time abroad! 
If I find some time I will make a pull request so you can review it when you are back.

Regards

**Comment by vikpe** [comment]
That would be nice (please include tests if you do)!

**Comment by vikpe** [comment]
@kavadas `getChildrenTree()` supports `options.sort` from `v2.0.13`, please try  it out.

I added tests on `options.sort` for:
* `getChildrenTree()`
* `getAllChildren()`
* `getAllImmediateChildren()`

**Comment by kavadas** [comment]
Thank you for your work. This implementation is really nice for small amount of data. When you have a large tree or you need to generate paginated content this cannot work. That's why I asked for sorting in DB level rather than the application level.

What I proposed was to remove the current document key from it's path. The path should include only the parents. This way we could sort in DB level with a simple query.  But I understand completely that this may requires a lot of changes and even a migration plan. 

Unfortunately I didn't have the time to create a pull request. If I find some time I will let you know.

Thanks again for the nice plugin!

**Comment by vikpe** [comment]
Alright! I'll consider it for the next major release.

**Comment by vikpe** [comment]
I've created [a new branch](https://github.com/vikpe/mongoose-mpath/tree/feature/rewrite-path) where the `path` is set [as described in the mongodb docs](https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-materialized-paths/).

This means that you can perform server side sorting.

**Example**
Given a structure such as:
* world (id: 1)
  * europe (id: 2)
    * sweden (id: 3)

**Current version** (2.x)
```
world.path` = '1'
europe.path` = '1#2'
sweden.path = '1#2#3'
```

**Modified version**
```
world.path = '' (empty string)
europe.path = '#1#'
sweden.path = '#1#2#'
```

It's is a breaking change and would be released as v3.0.

If you have the time, please try it out. My tests probably don't cover enough of use cases to release it yet.

**Comment by kavadas** [comment]
Thank you once again. 

I played around with materialized paths in general and it seems that even if you make the change I requested you still cannot get the ordering work as it should. 

In a real world scenario when you have hierarchical data like categories, you will also need a way to change the order for categories which belong to the same parent. This requires that the path is set based on the custom ordering value and not on the ID.

I don't think that this is something that needs to be added to your plugin. I apologise for the frustration. You may close this issue.

**Comment by vikpe** [comment]
Alright, thanks for the input.
