### ISSUE TITLE
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0

### ISSUE THREAD

**Issue by porvas** [vikpe/mongoose-mpath#2]
Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead

I believe you are using this at line: 43

var childStream = self.collection.find({path: {'$regex': childRegex}}).stream();

Can it be replaced with cursor() ?

Thanks

**Comment by vikpe** [comment]
**Short answer**: no

`this.model` is not available during `schema.pre('save')` and `collection.find().cursor()` is not a function.

If you try, you'll get:
```
Uncaught TypeError: self.collection.find(...).cursor is not a function
```
It might be possible to replace it in some way; however I'm not getting any deprecation warnings and all tests pass.
