### ISSUE TITLE
Please help with .getParent() function

### ISSUE THREAD

**Issue by Cool-Programmer** [vikpe/mongoose-mpath#22]
So i have an array of categories through which i'm looping in pug. There i need to display also parent category name. So when i do
`
each category, i in categories
    #{category.getParent()}
`
it prints just "Object Object" etc...
What can i do to get the category title and some other information?

**Comment by vikpe** [comment]
The parent is an object with properties, try `#{category.getParent().name}`.

**Comment by Cool-Programmer** [comment]
No, it always returns undefined, can you please help me with some other possible solution?
Is there a way to retrieve some data from the parent category through `category.parent.category_title`?

**Comment by vikpe** [comment]
This is most likely not a problem related to mongoose-mpath.

I need more context in order to help you. Eg, dump the parent object so I can see all the properties.

**Comment by Cool-Programmer** [comment]
So when i'm doing `` 
console.log(category.getParent())
`
it returns a doc file that looks something like this
Query {
  _mongooseOptions: {},
  _transforms: [],
  mongooseCollection:
   NativeCollection {
     collection: Collection { s: [Object] },
     opts:
      { bufferCommands: true,
        capped: false,
        '$wasForceClosed': undefined },
     name: 'categories',
     collectionName: 'categories',
     conn:
      NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        '$internalEmitter': [EventEmitter],
        _listening: false,
        _connectionOptions: [Object],
        name: 'likeblog_db',
        host: 'localhost',
        port: 27017,
        user: undefined,
        pass: undefined,
        client: [MongoClient],
        '$initialConnection': [Promise],
        db: [Db] },
     queue: [],
     buffer: false,
     emitter:
      EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  model:
ETC
`
but when i do 
`
console.log(await category.getParent());
`
it gives
`
{ view_count: 0,
  is_child_category: null,
  parent_category_id: null,
  category_level: 0,
  category_children: [],
  posts: [],
  _id: 5e13150f92bfa14f54f4d8a1,
  date_published: 2020-01-06T11:07:59.330Z,
  category_title: 'Спорт',
  category_meta_title: 'Спорт',
  category_meta_description: 'Спорт',
  is_published: true,
  show_in_menu: true,
  category_slug: 'sports',
  path: '5e13150f92bfa14f54f4d8a1',
  __v: 0 }
`
which is the desired one, but i can't use await inside pug template

**Comment by vikpe** [comment]
Yes `getParent()` is asynchronous, either use `await getParent()` or `getParent().then(...)`.

I'm not familiar with pug and its design patterns. Normally you would separate the data fetching (controller layer) from rendering (view layer).

**Comment by Cool-Programmer** [comment]
I'll try with the .then(...) one, thanks.
I know the separation thing, but i can't figure out a way to do so for separate items created from a loop
