### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by tranpham9999** [vikpe/mongoose-mpath#24]
How can i use with typescipt in nestjs?

**Comment by vikpe** [comment]
@tranpham9999 I'm not familiar with nestjs and I haven't tried using Mongoose with TypeScript.

A quick search on the topic:
* https://github.com/szokodiakos/typegoose
* [Complete guide for Typescript with Mongoose for Node.js](https://medium.com/@agentwhs/complete-guide-for-typescript-for-mongoose-for-node-js-8cc0a7e470c1)
* [Strongly typed models with Mongoose and TypeScript](https://medium.com/@tomanagle/strongly-typed-models-with-mongoose-and-typescript-7bc2f7197722)

**Comment by tranpham9999** [comment]
I try to use it in my project with nestjs but the library only create database and all function not helpful....sr my english so bad :3

**Comment by zhaydexxa** [comment]
hi @tranpham9999 

example menu.schema.ts
`import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, SchemaTypes, Document } from 'mongoose';
import * as MpathPlugin from 'mongoose-mpath';

export type MenuDocument = HydratedDocument<Menu>;

@Schema({
  strictQuery: false,
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
})
export class Menu {
  @Prop({ required: true })
  name?: string;

  @Prop()
  url?: string;

  @Prop()
  href?: string;

  @Prop()
  icon?: string;

  @Prop({ type: SchemaTypes.Mixed })
  badge?: {
    variant?: string;
    text?: string;
  };

  @Prop({ default: false })
  divider?: boolean;

  @Prop({ default: false })
  title?: boolean;

  @Prop({ type: SchemaTypes.Mixed })
  attributes?: {
    disabled?: boolean;
    target?: string;
  };

  @Prop({ required: true })
  state?: string;

  @Prop({ default: false })
  root?: boolean;

  @Prop({ default: 0 })
  sequence?: number;

  // mongoose mpath fields
  path?: string;
  parent?: any;
  children?: any[];
  level?: number;

  // mongoose mpath functions
  getParent: () => Promise<Menu>;
  getAllChildren: (
    conditions?: {},
    fields?: any,
    options?: {},
  ) => Promise<Menu[]>;
  getChildrenTree: (
    filters?: {},
    fields?: any,
    options?: {},
    populate?: string,
    minLevel?: number,
    maxLevel?: number,
    rootDoc?: Document,
  ) => Promise<Menu[]>;
}

export const MenuSchema = SchemaFactory.createForClass(Menu);
MenuSchema.plugin(MpathPlugin, { modelName: 'Menu' });
`
