### ISSUE TITLE
Question: How to use DELETE to remove all immediate children?

### ISSUE THREAD

**Issue by JakeSchroeder** [vikpe/mongoose-mpath#26]
Hello when using this libarary and attempting to remove a parent node with children I would assume REPARENT would move child nodes up a level to the nearest ancestor and DELETE would remove children of the parent node. However, both DELETE and REPARENT do the same thing in that context.

How can I remove all children of a parent node instead of moving them up to nearest ancestor?

I can provide code examples if neccessary. Thanks for this awesome library!!!!!

**Comment by vikpe** [comment]
@JakeSchroeder your assumption is correct.

Initialize the plugin with the option `onDelete` set to `DELETE` (case-sensitive).

```javascript
MySchema.plugin(MpathPlugin, {
  onDelete: 'DELETE',
});
```

If it's still not working as expected, please paste your model/schema code so I can take a look.
