### ISSUE TITLE
Can I set maxLevel when use getChildrenTree

### ISSUE THREAD

**Issue by vuonghungvinh** [vikpe/mongoose-mpath#28]
ex: I just want get level 1 and 2, I will set maxLevel: 2
this is can?

**Comment by vikpe** [comment]
@vuonghungvinh sorry for my delayed reply. At the time of your question: **no**. 

However it makes sense to have `maxLevel` when there is a `minLevel`. I added parameter `maxLevel` in version `2.3.0` which is now released.
