### ISSUE TITLE
How to dynamically set the parent?

### ISSUE THREAD

**Issue by nerijunior** [vikpe/mongoose-mpath#3]
Hi, exists some way to dynamically set the parent or change the parent?

Imagine this:
- Father 1
-- Child
--- Another Child
- Father 2

I need to change the `child` from Father 1 to Father 2.

Thanks.

**Comment by nerijunior** [comment]
Sorry about that I looked at another plugin README and open the issue here. :(

My bad.

**Comment by vikpe** [comment]
No problem mate :)

**Comment by yam-b** [comment]
Sorry but how _do_ you do that?

**Comment by vikpe** [comment]
@yam-b thanks for your notice.

`findByIdAndUpdate` doesn't trigger document middleware.

From the [middleware docs](http://mongoosejs.com/docs/middleware.html):
> Document middleware is supported for the following document functions. In document middleware functions, this refers to the document.
>
> init
> validate
> save
> remove

I'll see if I can get it to work somehow - feel free to suggest a solution!

**Comment by Bynx** [comment]
Does anyone have a working example of the



> Sorry but how _do_ you do that?
> 
> It states "The path is used for recursive methods and is kept up to date by the plugin if the parent is changed." but when I use findByIdAndUpdate, the path won't change to match.
> 
> Edit: Digged through the tests, and it seems like FindOne > .set > .save works. I would suggest making reparenting work with findByIdAndUpdate.

Can anyone provide an example of a PUT request for changing the parent using FindOne > .set > .save as mentioned above? If async/await is used, that would be even better.
