### ISSUE TITLE
Question: Why children attribute is always empty

### ISSUE THREAD

**Issue by dimitardanailov** [vikpe/mongoose-mpath#30]
Greetings, 

The plugin is wonderful and you have my apologies. I've implemented the example from the Readme file: 

```javascript
const europe = new LocationModel({name: 'europe'});
const sweden = new LocationModel({name: 'sweden', parent: europe});
const stockholm = new LocationModel({name: 'stockholm', parent: sweden});
const skansen = new LocationModel({name: 'skansen', parent: sweden});
const subSkansen = new LocationModel({name: 'subSkansen', parent: skansen});

await europe.save();
await sweden.save();
await stockholm.save();
await skansen.save();
await subSkansen.save();
```

I can't understand: What's the benefit `children` property to be stored in the db collection set with empty value:

<img width="1627" alt="Screen Shot 2020-11-21 at 1 12 06 AM" src="https://user-images.githubusercontent.com/2182018/99858666-bfecfb80-2b96-11eb-8827-f84aac6e1fe0.png">

I'm not an expert with this plugging. What I found: The `children` property is a valuable asset in the following example:

```javascript
const location = await LocationModel.findOne({name: 'europe'});
const tree = await location.getChildrenTree({});
console.log('location tree', tree[0]);
```

The response is: 
<img width="834" alt="Screen Shot 2020-11-21 at 1 00 06 AM" src="https://user-images.githubusercontent.com/2182018/99858713-d430f880-2b96-11eb-9e5f-f85e85f569d0.png">

My questions are: `level` is a virtual property which is nice.  
#1 Why children attribute is not a virtual property ?
#2 Why children attribute is stored as an empty array in the database ?

**Comment by vikpe** [comment]
@dimitardanailov You are not allowed to dynamically extend mongoose documents with new properties. I added the property in order to have a placeholder for the children that is populated using `getChildrenTree`. 

However it's possible that a virtual property will do just fine, I'll try it out. Thank you for highlighting this.

**Comment by dimitardanailov** [comment]
@vikpe 

Thank you very much for the clarification and fast response. I've a better overview why `children attribute` is an empty value and why the property is not a virtual property.
