### ISSUE TITLE
Doesnt save children in node

### ISSUE THREAD

**Issue by FBurner** [vikpe/mongoose-mpath#38]
Hi, seems it doesnt save the children with mongoose 

5.13.7

    const organisationNode = new this.organisationNode({
      _id: new Types.ObjectId(),
      name,
      parent: rootNode,
      originalId
    });
    rootNode.save();
    return organisationNode.save();

no children can be seen in rootnode

**Comment by vikpe** [comment]
@FBurner is this still an issue?

(sorry for a very late reply)
