### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by paullbn** [vikpe/mongoose-mpath#4]
Hello,

When creating a document with an existing parent, i'm getting the following error:

```
TypeError: Cannot read property 'length' of undefined
    at onStreamData (C:\...\node_modules\mongoose-mpath\lib\mpath.js:46:81)
    at C:\...\node_modules\stream-worker\stream-worker.js:63:39
```

mpath tries, in preSave, to updateChildPaths of the recently created document, with an undifined pathToReplace, because document.path is not set yet.

There is a simplified way i'm doing the creation:
```
...
  study.state = 'Published';
  study.save()
    .then(async (savedStudy) => {

            try {
              var s = new Study({
                name: 'blabla',
                state: 'Published',  
                parent: study,
              })
              await s.save()
            } catch (e) {
              console.log(e);
            }
        return res.json(savedStudy)
      })
```
the study document already has a correct path attribute

I temporaly fixed my problem replacing mpath.js line 67 by:
`        if (!this.isNew && hasModifiedParent) { // Rewrite child paths when parent is changed`

Am I doing something wrong during creation?

Thanks, 
Paul

**Comment by vikpe** [comment]
@paullbn hich version of mongoose are you using? 

I'll try to replicate the error. However, I'll be away for the next two weeks without a computer.

You are very welcome to write a test that confirms the bug, write a solution and post a pull request.

**Comment by paullbn** [comment]
My bad... I was using an outdated version of mongoose... Closing the issue 

Thank's for your quick answer and your great plugin ;)

**Comment by haikarthikssk** [comment]
@paullbn  You saved my day !.. thanks.
