### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by StefanoDeVuono** [vikpe/mongoose-mpath#5]
@vikpe Any interest in promisification of this module?

**Comment by vikpe** [comment]
@StefanoDeVuono sounds like a good idea. I should also update this plugin to support the latest version of mongoose. However I'm busy with several other projects at the moment.

**Comment by StefanoDeVuono** [comment]
Cool. I'll look into it.

**Comment by florianbepunkt** [comment]
@vikpe @StefanoDeVuono : I ported this library to use lates mongoose version and to use promises instead of callbacks. Also refactored the code to ES6 and in tests used async / await to make tests more concise and readable. Added PR #6

**Comment by vikpe** [comment]
@florianbepunkt thanks for the pr! I'll review and provide feedback when I get back from my trip (tomorrow).

**Comment by vikpe** [comment]
Thanks to @florianbepunkt methods now return promises and supports mongoose 5.x.
