### ISSUE TITLE
Methods return plain objects instead of mongoose documents?

### ISSUE THREAD

**Issue by florianbepunkt** [vikpe/mongoose-mpath#7]
Not 100% sure but I believe that `getChildrenTree` method is returning plain objects instead of mongoose documents.

If I `use collection.find()` then it returns an array of mongoose documents where for example all instance methods are available. If I use `collection.getChildrenTree()`, the instance methods are not available.

**Comment by florianbepunkt** [comment]
Okay, sorry… have to reopen this. There is an issue as the default value for lean always proceeds. So my sugeestion would be to simply ommit the line `options.lean = 1;` in `schema.statics.getChildrenTree`  https://github.com/vikpe/mongoose-mpath/blob/02dd7928e188146157063e6d5c5e0f54a924fb64/lib/mpath.js#L214 as this would be more on par with mongoose defaults and would also allow for lean to be set true/false in arguments passed to the method,

**Comment by vikpe** [comment]
@florianbepunkt I've changed the default value, thanks for your notice!
